#variableDefinitions.py

import olexex
import programSettings
from variables import *
import variableFunctions
from olexFunctions import OlexFunctions
OV = OlexFunctions()

def guiVariables():
  return dict(
    gui_logo_colour='#6464a0',
    gui_skin_name='default',
    gui_skin_extension='n/a',
    gui_skin_logo_name=r'gui/images/src/default.png',
    
    gui_purple='#a245a2',
    gui_red='#ff0000',
    gui_orange='#ff8f00',
    gui_green='#018F1E',
    gui_grey='#555555',
    
    gui_html_base_colour='#00ff00',
    gui_html_bg_colour='#ffffff',
    gui_html_input_bg_colour='#F3F3F3',
    gui_html_font_colour='#6f6f8b',
    gui_html_font_name='Verdana',
    gui_html_table_bg_colour='#F3F3F3',
    gui_html_table_firstcol_colour='#E9E9E9',
    gui_html_highlight_colour=OV.FindValue('gui_html_highlight_colour','#ff7800'),
    gui_html_link_colour='#6f6f8b',
    gui_html_icon_size='22',
    gui_html_font_size='2',
    
    gui_image_font_name='Vera',
    gui_timage_colour='#6464a0',
    gui_timage_font_colour='#ff0000',
    gui_snumtitle_colour='#6464a0',
    gui_snumtitle_font_colour='#ff0000',
    gui_tab_colour='#ff0000',
    gui_tab_font_colour='#ff0000',
    
    gui_infobox_text='2053;2143326838;2143979345',
    gui_infobox_plane='2053;2136422952;2137144606',
    
    gui_htmlpanelwidth='290',
    gui_grad_top_left='#05053c',
    gui_grad_top_right='#05053c',
    gui_grad_bottom_left='#ffffff',
    gui_grad_bottom_right='#ffffff',
    gui_language_encoding=OV.CurrentLanguageEncoding(),
    gui_gui_MainToolbarTabButtonActive='none',
    
    gui_use_fader='false',
    gui_shelx_restraints='--',
    gui_shelx_constraints='--',
    gui_archive_last='--',
  )

def snumVariables():
  return {
    'snum_solution_program':Variable('?', PermittedValues(olexex.SPD.programs.keys()), onChange=olexex.onSolutionProgramChange),
    'snum_solution_method':Variable('?', onChange=olexex.onSolutionMethodChange),
    #'snum_refinement_formula':Variable(''),
    
    'snum_refinement_program':Variable('?', PermittedValues(olexex.RPD.programs.keys()), onChange=olexex.onRefinementProgramChange),
    'snum_refinement_method':Variable('?', onChange=olexex.onRefinementMethodChange),
    'snum_refinement_sg':Variable(OV.olex_function(r'sg(%n)')),
    'snum_refinement_sg_list':Variable('--'),
    'snum_refinement_max_cycles':Variable(4,Range(min=0),onChange=programSettings.onMaxCyclesChange),
    'snum_refinement_max_peaks':Variable(20,Range(min=0),onChange=programSettings.onMaxPeaksChange),
    'snum_refinement_update_weight':Variable(False),
    'snum_refinement_original_formula':Variable(''),
    'snum_refinement_Z_prime':Variable(1.0,Range(min=0.0)),
    'snum_refinement_auto_assignQ':Variable(2.0,Range(min=0.0)),
    'snum_refinement_auto_max_peaks':Variable(False),
    'snum_refinement_auto_pruneU':Variable(0.1,Range(min=0.0)),
    'snum_refinement_auto_pruneQ':Variable(1.5,Range(min=0.0)),
    'snum_refinement_auto_promote':Variable(0.1),
    'snum_refinement_auto_assemble':Variable(False),
    'snum_refinement_auto_tidy':Variable(False),
    'snum_refinement_last_R1':Variable('n/a'),
    
    'snum_shelx_output':Variable(True),
   
    'snum_history_current_solution':Variable("Solution 01"),
    'snum_history_next_solution':Variable("Solution 01"),
    'snum_history_autochem_next_solution':Variable("Autochem 01"),
    
    'snum_autochem_current_solution':Variable("Autochem 01"),
    'snum_auto_hydrogen_naming':Variable('checked'),
    
    'snum_dimas_progress_status':Variable('?'),
    'snum_dimas_progress_comment':Variable('?'),
    'snum_dimas_reference_ccdc_number':Variable('?'),
    'snum_dimas_reference_csd_refcode':Variable('?'),
    'snum_dimas_reference_publ_authors':Variable('?'),
    'snum_dimas_reference_journal_name':Variable('?'),
    'snum_dimas_reference_journal_volume':Variable('?',Range(min=1),int),
    'snum_dimas_reference_journal_pages':Variable('?',Range(min=1),int),
    'snum_dimas_reference_journal_year':Variable('?',Range(1800,2100),int),
    'snum_dimas_reference_comment':Variable('?'),
    
    'snum_metacif_atom_sites_solution_primary':Variable('?',PermittedValues((
      '?','difmap','vecmap','heavy','direct','geom','disper','isormor','notdet','dual','other'))),
    'snum_metacif_cell_measurement_reflns_used':Variable('?',Range(min=0.0),int),
    'snum_metacif_cell_measurement_theta_max':Variable('?',Range(0.0,90.0),float),
    'snum_metacif_cell_measurement_theta_min':Variable('?',Range(0.0,90.0),float),
    'snum_metacif_cell_measurement_temperature':Variable('?',Range(min=0.0)),
    'snum_metacif_chemical_name_systematic':Variable('?'),
    'snum_metacif_computing_cell_refinement':Variable('?'),
    'snum_metacif_computing_data_collection':Variable('?'),
    'snum_metacif_computing_data_reduction':Variable('?'),
    'snum_metacif_computing_molecular_graphics':Variable(variableFunctions.getOlex2VersionInfo()),
    'snum_metacif_computing_publication_material':Variable(variableFunctions.getOlex2VersionInfo()),
    'snum_metacif_computing_structure_solution':Variable('?'),
    'snum_metacif_diffrn_ambient_temperature':Variable('?',Range(min=0.0)),
    'snum_metacif_diffrn_special_details':Variable('?'),
    'snum_metacif_diffrn_measurement_device':Variable('?'),
    'snum_metacif_diffrn_measurement_device_type':Variable('?'),
    'snum_metacif_diffrn_measurement_method':Variable('?'),
    'snum_metacif_diffrn_measurement_details':Variable('?'),
    'snum_metacif_diffrn_radiation_collimation':Variable('?'),
    'snum_metacif_diffrn_radiation_filter_edge':Variable('?',Range(min=0.0),float),
    'snum_metacif_diffrn_radiation_inhomogeneity':Variable('?',Range(min=0.0),float),
    'snum_metacif_diffrn_radiation_monochromator':Variable('?'),
    'snum_metacif_diffrn_radiation_polarisn_norm':Variable('?',Range(min=-180.0,max=180.0)),
    'snum_metacif_diffrn_radiation_polarisn_ratio':Variable('?',Range(min=0.0),float),
    'snum_metacif_diffrn_radiation_probe':Variable('?',PermittedValues(('x-ray','neutron','electron','gamma'))),
    'snum_metacif_diffrn_radiation_type':Variable('?'),
    'snum_metacif_diffrn_radiation_xray_symbol':Variable('?',PermittedValues(('K-L~3~','K-L~2~','K-M~3~','K-L~2,3~'))),
    'snum_metacif_diffrn_radiation_wavelength':Variable('?',Range(min=0.0),float),
    'snum_metacif_diffrn_source':Variable('?'),
    'snum_metacif_diffrn_source_current':Variable('?',Range(min=0.0),float),
    'snum_metacif_diffrn_source_power':Variable('?',Range(min=0.0),float),
    'snum_metacif_diffrn_source_voltage':Variable('?',Range(min=0.0),float),
    'snum_metacif_diffrn_source_target':Variable('?'),
    'snum_metacif_diffrn_source_type':Variable('?'),
    'snum_metacif_diffrn_refln_scan_width':Variable('?',Range(min=0.0),float),
    'snum_metacif_diffrn_detector':Variable('?'),
    'snum_metacif_diffrn_detector_type':Variable('?'),
    'snum_metacif_diffrn_detector_area_resol_mean':Variable('?',Range(min=0.0),float),
    'snum_metacif_diffrn_orient_matrix_UB_11':Variable('?',None,float),
    'snum_metacif_diffrn_orient_matrix_UB_12':Variable('?',None,float),
    'snum_metacif_diffrn_orient_matrix_UB_13':Variable('?',None,float),
    'snum_metacif_diffrn_orient_matrix_UB_21':Variable('?',None,float),
    'snum_metacif_diffrn_orient_matrix_UB_22':Variable('?',None,float),
    'snum_metacif_diffrn_orient_matrix_UB_23':Variable('?',None,float),
    'snum_metacif_diffrn_orient_matrix_UB_31':Variable('?',None,float),
    'snum_metacif_diffrn_orient_matrix_UB_32':Variable('?',None,float),
    'snum_metacif_diffrn_orient_matrix_UB_33':Variable('?',None,float),
    'snum_metacif_exptl_absorpt_correction_type':Variable('?',PermittedValues((
      '?','analytical','cylinder','empirical','gaussian','integration','multi-scan','none','numerical',
      'psi-scan','refdelf','sphere',))),
    'snum_metacif_exptl_absorpt_correction_T_max':Variable('?',Range(0.0,1.0),float),
    'snum_metacif_exptl_absorpt_correction_T_min':Variable('?',Range(0.0,1.0),float),
    'snum_metacif_exptl_absorpt_process_details':Variable('?'),
    'snum_metacif_exptl_crystal_density_meas':Variable('.',Range(min=0.00001),float),
    'snum_metacif_exptl_crystal_colour':Variable('?'),
    'snum_metacif_exptl_crystal_colour_primary':Variable('?',PermittedValues((
      '?','colourless','white','black','gray','brown','red','pink','orange','yellow','green','blue','violet')), onChange=olexex.onCrystalColourChange),
    'snum_metacif_exptl_crystal_colour_lustre':Variable('?',PermittedValues(('?','metallic','dull','clear')), onChange=olexex.onCrystalColourChange),
    'snum_metacif_exptl_crystal_colour_modifier':Variable('?',PermittedValues((
      '?','light','dark','whiteish','blackish','grayish','brownish','reddish','pinkish','orangish','yellowish','greenish','bluish')), onChange=olexex.onCrystalColourChange),
    'snum_metacif_exptl_crystal_size_min':Variable('?',Range(min=0.0),float),
    'snum_metacif_exptl_crystal_size_mid':Variable('?',Range(min=0.0),float),
    'snum_metacif_exptl_crystal_size_max':Variable('?',Range(min=0.0),float),
    'snum_metacif_exptl_crystal_description':Variable('?'),
    'snum_metacif_exptl_crystal_recrystallization_method':Variable('?'),
    'snum_metacif_exptl_crystal_preparation':Variable('?'),
    'snum_metacif_exptl_special_details':Variable('?'),
    'snum_metacif_symmetry_cell_setting':Variable('?',PermittedValues((
      '?','triclinic','monoclinic','orthorhombic','tetragonal','rhombohedral','trigonal','hexagonal','cubic'))),
    'snum_metacif_symmetry_space_group_name_H-M':Variable('?'),
    'snum_metacif_symmetry_cell_setting':Variable('?'),
    'snum_metacif_sad_file':Variable('?'),
    'snum_metacif_pcf_file':Variable('?'),
    'snum_metacif_p4p_file':Variable('?'),
    'snum_metacif_smart_file':Variable('?'),
    'snum_metacif_saint_file':Variable('?'),
    'snum_metacif_frames_file':Variable('?'),
    'snum_metacif_integ_file':Variable('?'),
    'snum_metacif_cad4_file':Variable('?'),
    #'snum_report_diffractometer_definition_file':Variable('?'),
    'snum_metacif_publ_contact_author_name':Variable('?'),
    'snum_metacif_publ_author_names':Variable('?'),
    'snum_metacif_publ_contact_letter':Variable('?'),
    'snum_metacif_publ_author_name_list':Variable('?'),
    'snum_metacif_publ_requested_journal':Variable('?'),
    'snum_metacif_list_sad_files':Variable('--'),
    'snum_metacif_list_pcf_files':Variable('--'),
    'snum_metacif_list_p4p_files':Variable('--'),
    'snum_metacif_list_smart_files':Variable('--'),
    'snum_metacif_list_saint_files':Variable('--'),
    'snum_metacif_list_frames_files':Variable('--'),
    'snum_metacif_list_integ_files':Variable('--'),
    'snum_metacif_list_cad4_files':Variable('--'),
    
    'snum_report_date_collected':Variable('?'),
    'snum_report_date_submitted':Variable('?'),
    'snum_report_operator':Variable('?'),
    'snum_report_submitter':Variable('?'),
    'snum_report_diffractometer':Variable('?'),
    'snum_report_title':Variable(OV.FileName()),
    'snum_report_image':Variable('%s/screenshot.png' %OV.FilePath()),
    'snum_report_image_size':Variable(800,Range(min=0)),
    
    'snum_user_input_variables':Variable('--'),
    'snum_eden_fine_value':Variable(0),
    'snum_eden_coarse_value':Variable(1),
    #'snum_map_type':'diff',
    #'snum_map_source':'olex',
    #'snum_map_view':'wire',
    'snum_map_view':Variable('wire'),
    'snum_map_source':Variable('olex'),
    'snum_map_type':Variable('diff'),
    'snum_map_resolution':Variable(0.1),
    
    #'snum_map_button_txt':'Calculate Electron Density',
    'snum_calcvoid_value':'-1',
    'snum_calcvoid_view':'wire',
    #'snum_calcvoid_button_txt':'Calculate Voids',
    'snum_olex_conres':'RRINGS',
  }

def userVariables():
  return {
    'user_alert_delete_history':Variable('Y'),
    'user_alert_overwrite_history':Variable('Y'),
    'user_alert_uninstall_plugin':Variable('Y'),
    'user_refinement_program':Variable('ShelXL'),
    'user_refinement_method':Variable('Least Squares'),
    'user_solution_program':Variable('ShelXS'),
    'user_solution_method':Variable('Direct Methods'),
    'user_refinement_max_cycles':Variable(4,Range(min=0)),
    'user_refinement_max_peaks':Variable(20,Range(min=0)),
    'user_refinement_update_weight':Variable(False),
    'user_refinement_auto_assignQ':Variable(2.0,Range(min=0.0)),
    'user_refinement_auto_pruneU':Variable(0.1,Range(min=0.0)),
    'user_refinement_auto_pruneQ':Variable(1.5,Range(min=0.0)),
    'user_refinement_auto_assemble':Variable(False),
    'user_refinement_auto_promote':Variable(0.1),
    'user_refinement_auto_tidy':Variable(True),
    'user_report_style':Variable('default'),
    'user_report_journal_style':Variable('rsc'),
  }